#!/bin/sh
#!/bin/bash

USUARIO=/DATA/a_modulo-3/usuario.txt

# Leer la primera linea del archivo
USER=$(head -1 $USUARIO | tail -1)

F1=/DATA/a_modulo-7/nro_screen_telegram.txt


DB_REP=/DATA/a_modulo-7/db_rep.txt
DB_AUT=/DATA/a_modulo-7/db_aut.txt

# Leer Numero de sesion
NUM=$(head -1 $F1 | tail -1)

sleep 2
screen -S $NUM.telegram-session -p 0 -X stuff "`printf "send_text $USER $DB_REP\r"`";

sleep 2
screen -S $NUM.telegram-session -p 0 -X stuff "`printf "send_text $USER $DB_AUT\r"`";

