#!/bin/bash

r=$RANDOM
echo "$r"


CLIENT=/DATA/a_modulo-3/cliente-seguro.txt

# Leer la primera linea del archivo
CLI=$(head -1 $CLIENT | tail -1)


F1=/DATA/a_modulo-7/nro_screen_sqsh.txt

# Leer Numero de sesion
NUM=$(head -1 $F1 | tail -1)

db=/DATA/a_modulo-7/db_rep.txt

# Leer Nombre de la db
DB=$(head -1 $db | tail -1)


screen -S $NUM.telegram-sqsh -p 0 -X stuff "`printf "/usr/local/bin/sqsh -S SOMSQL\r"`";

screen -S $NUM.telegram-sqsh -p 0 -X stuff "`printf "exec $DB $CLI, $CLI$r\r"`";

#screen -S $NUM.telegram-sqsh -p 0 -X stuff "`printf "exec $DB $CLI, gus\r"`";

screen -S $NUM.telegram-sqsh -p 0 -X stuff "`printf "\go\r"`";

#screen -S $NUM.telegram-sqsh -p 0 -X stuff "`printf "\go >/DATA/SHARED/$CLI-$r.txt\r"`";

sleep 3
screen -S $NUM.telegram-sqsh -p 0 -X stuff "`printf "quit\r"`";




USUARIO=/DATA/a_modulo-3/usuario-seguro.txt

# Leer la primera linea del archivo
USER=$(head -1 $USUARIO | tail -1)

F2=/DATA/a_modulo-7/nro_screen_telegram.txt

# Leer Numero de sesion
NUM2=$(head -1 $F2 | tail -1)


sleep 1
screen -S $NUM2.telegram-session -p 0 -X stuff "`printf "send_document $USER /DATA/SHARED/$CLI$r.html\r"`";

