#!/bin/bash



F1=/DATA/s_1/a_modulo-3/usuario.txt
F2=/DATA/s_1/a_modulo-3/usuario-s.txt


# Leer la primera linea del archivo
USER=$(head -1 $F1 | tail -1)

# Leer la primera linea del archivo
USER2=$(head -1 $F2 | tail -1)

F3=/DATA/s_1/a_modulo-7/nro_screen_telegram.txt

# Leer Numero de sesion
NUM=$(head -1 $F3 | tail -1)

screen -S $NUM.telegram-session-s1 -p 0 -X stuff "`printf "create_secret_chat $USER\r"`";

sleep 3
screen -S $NUM.telegram-session-s1 -p 0 -X stuff "`printf "msg $USER2 Conexion segura establecida\r"`";

