#!/bin/sh
#!/bin/bash

F1=/DATA/s_1/a_modulo-7/nro_screen_telegram.txt

# Leer Numero de sesion
NUM=$(head -1 $F1 | tail -1)

#sleep 10
screen -S $NUM.telegram-session-s1 -p 0 -X stuff "`printf "status_online\r"`";


